kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ index .Values.labels "infra-env" }}-{{ index .Values.labels "infra-product" }}-admin
  namespace: {{ .Values.namespace }}
  labels:
    infra-env: {{ index .Values.labels "infra-env" }} 
    infra-service: {{ index .Values.labels "infra-product" }} 
    infra-product: role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]